### ISSUE TITLE
Company Profile: Images don't open in lightboxes

### ISSUE THREAD

**Issue by bernardtitan** [titan-cebu/Drillne#15]

**Comment by ermatitan** [comment]
Cannot verify due to issue #27

**Comment by ermatitan** [comment]
Not fix.

**Comment by ermatitan** [comment]
Not fix

**Comment by rexcebudigital** [comment]
Hi Erma, It is now okay on my end, please see attached screenshot. Kindly let me know if this issue is still not solve. Thanks.
![screenshot](https://cloud.githubusercontent.com/assets/11186391/9033911/3eb4a1a6-39fe-11e5-9bb0-a333613d41ff.jpg)
