### ISSUE TITLE
General: The Extended Album should be styled identically to the Compact Album to make them interchangable for the Project Portfolio page

### ISSUE THREAD

**Issue by bernardtitan** [titan-cebu/Drillne#19]

**Comment by ermatitan** [comment]
Not fix

**Comment by ermatitan** [comment]
The extended album only displays the smaller thumbnail version of the compact album/gallery.

**Comment by rexcebudigital** [comment]
Hi Erma, kindly set the dimension on extended album if you will test or create an extended on another page. See screenshot below.

![screenshot](https://cloud.githubusercontent.com/assets/11186391/9000249/da19d68c-3776-11e5-8745-496a85769dc3.jpg)

**Comment by ermatitan** [comment]
Hello Rex, 

As per conversation with Bernard, the client/user should not set any settings when adding extended album. Thanks
