### ISSUE TITLE
Contact Us: Subject field is gone

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Drillne#38]
![image](https://cloud.githubusercontent.com/assets/12791909/8949758/1789469e-35ea-11e5-94d5-532bb7cb3ebb.png)

**Comment by rexcebudigital** [comment]
Hi Erma, we have discuss this issue when Bernard came here for a meeting. We agreed to hide the subject because its redundant. Kindly ask Bernard about this. Thanks.
