### ISSUE TITLE
All Pages: Body text should use Arial instead of Helvetica Neue

### ISSUE THREAD

**Issue by bernardtitan** [titan-cebu/Drillne#5]

**Comment by ermatitan** [comment]
Not fix on news page.

![image](https://cloud.githubusercontent.com/assets/12791909/8869824/290ca456-321b-11e5-9501-26ecc220295f.png)

**Comment by christiancebudigital** [comment]
Hi Erma,
please see attached screenshot
![font](https://cloud.githubusercontent.com/assets/11186331/8926015/fd2b3650-353e-11e5-96bc-c75c712b6b3d.jpg), we are using font: arial

**Comment by bernardtitan** [comment]
This was fixed on all other pages
