### ISSUE TITLE
Our Services : Where does page link label be displayed? Currently any changes on this label will not reflect on the Services Page. 

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Drillne#53]
![image](https://cloud.githubusercontent.com/assets/12791909/9029242/64c4c8ee-39c2-11e5-84d8-87a7c963d11f.png)

**Comment by rexcebudigital** [comment]
Hi Erma, I already deleted the ACF for it because we decided to link the services to the contact page.
